version: '3.8'

services:
  spring-app-a:
    build: ./spring-app-a
    container_name: spring-app-a
    ports:
      - "8081:8081"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "true"
        tag: "spring-app-a"
    networks:
      - app-network
    depends_on:
      - fluent-bit-a

  spring-app-b:
    build: ./spring-app-b
    container_name: spring-app-b
    ports:
      - "8082:8082"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "true"
        tag: "spring-app-b"
    networks:
      - app-network
    depends_on:
      - fluent-bit-b

  fluent-bit-a:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit-a
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
    networks:
      - app-network

  fluent-bit-b:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit-b
    ports:
      - "24226:24226"
      - "24226:24226/udp"
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
    networks:
      - app-network


  fluentd:
    image: fluent/fluentd:latest
    container_name: fluentd
    ports:
      - "24225:24225"
      - "24225:24225/udp"
    volumes:
      - ./fluentd/conf:/fluentd/etc:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
